### ISSUE TITLE
Missing mv

### ISSUE THREAD

**Issue by hansaya** [Wonderfall/docker-rtorrent#3]
Love the image but need `mv` command to move downloaded files from incomplete to complete. Took me while to figure out why my .rc file wasn't working :)

for something like this
```
method.insert = d.move_to_complete, simple, "execute=/usr/local/bin/rtunrar,$argument.2=; \
      d.directory.set=$argument.1=; \
      execute=mkdir,-p,$argument.1=; \
      execute=mv,$argument.0=,$argument.1=; \
      d.save_full_session="
method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.get_finished_dir=,$d.base_path="
```

This way I can prevent anything from grabbing the files from the download folder prematurely. Incomplete->unrar->complete->radarr

**Comment by cirdanmiriel** [comment]
Hi, and congrats on your job here (and on the previous rtorrent-flood docker hub repo :) ).
I spent way too much time figuring out why the downloaded files moving features in my .rc file wasn't working, only to find out that mv and mkdir weren't present in the image, so I highly second @hansaya in this ticket, if by any way you could just add at least mv and mkdir (if I'm right they are already in the coreutils imported for the building of your rtorrent image, no?), well, this would be a lifesaver! (I am unfortunately not a docker master enough to clone your repo and adapt it :) )
Many thanks!

**Comment by Wonderfall** [comment]
Fix should be simple:

```
# FROM ghcr.io/wonderfall/rtorrent
COPY --from=gcr.io/distroless/static:debug /busybox/mv /bin/mv
COPY --from=gcr.io/distroless/static:debug /busybox/mkdir /bin/mkdir
```

Add those instructions to your Dockerfile. You can even reuse my own image so you don't have to build it again. Tell me if that works for you!

**Comment by cirdanmiriel** [comment]
First, thank you for taking time to answer us.
It works! :) 

I'm no Docker expert but I managed to do it so I'm pretty sure anyone can! ^^'
As far as I'm concerned, this ticket could be closed then.
